### ISSUE TITLE
ParseException in Polygon

### ISSUE THREAD

**Issue by xnomagichash** [Sentenai/solr-query#8]
java.text.ParseException: Unknown Shape definition [POLYG
ON(-10.0 30.0,-40.0 40.0,-10.0 -20.0,40.0 20.0,0.0 0.0,-10.0 30.0)]

According to Solr docs, polygon should be this:
`POLYGON((-10 30, -40 40, -10 -20, 40 20, 0 0, -10 30))`

I believe what's missing is the extra set of parens.

**Comment by xnomagichash** [comment]
Ok, maybe not the extra parens. It seems lenient. This comes out with no error:

`{!field f=geo}Intersects(POLYGON(-10 30, -40 40, -10 -20, 40 20, 0 0, -10 30))`

**Comment by xnomagichash** [comment]
Doesn't look like it's the parens. Looks like some other problem:

https://wiki.apache.org/solr/SolrAdaptersForLuceneSpatial4#Search

**Comment by xnomagichash** [comment]
```
SearchQueryRequest {q = "(_yz_rb:00007ba6h9i8Asf\\- AND (t:[\"1679-06-12T00:00:00Z\" TO \"2038-04-23T00:00:00Z\"} AND i.CA-1Z2EXL0YmjdDz_rpt:\"Intersects(POLYGON(-10.0 30.0,-40.0 40.0,-10.0 -20.0,40.0 20.0,0.0 0.0,-10.0 30.0))\"))", index = "0000", rows = Just 1, start = Nothing, sort = Just "t asc", filter = Nothing, df = Nothing, op = Nothing, fl = fromList [], presort = Nothing}
```

**Comment by mitchellwrosen** [comment]
We discovered this was due to a missing schema entry

**Comment by xnomagichash** [comment]
This is incredibly painful. Solr doesn't come with the necessary Jar to make this work.
